ALTER TABLE USER ALTER COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE AUTHORITY ALTER COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE AUTHORITY ALTER COLUMN USER_ID BIGINT AUTO_INCREMENT;
ALTER TABLE ACTIVITY ALTER COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE ACTIVITY ALTER COLUMN AUTHORITY_ID BIGINT AUTO_INCREMENT;
