ALTER TABLE USER ADD VERSION BIGINT;
UPDATE USER SET VERSION = 1;

ALTER TABLE AUTHORITY ADD VERSION BIGINT;
UPDATE AUTHORITY SET VERSION = 1;

ALTER TABLE ACTIVITY ADD VERSION BIGINT;
UPDATE AUTHORITY SET VERSION = 1;
